#!/bin/bash
# For Mac + Linux:
docker run -it --rm --name build-che                \
           -v "$HOME/.m2:/home/user/.m2"            \
           -v "$PWD":/home/user/che-build           \
           -w /home/user/che-build                  \
           codenvy/che-dev                          \
           mvn -DskipTests=true                     \
               -Dfindbugs.skip=true                 \
               -Dgwt.compiler.localWorkers=2 -T 1C  \
               -Dskip-validate-sources              \
               clean install                        \

